# -*- coding: utf-8 -*-
"""Codsoft_task_3(Password_Generator).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11bw_TtKCCgV156L4UPoKWYtPwrIeahdW
"""

import random as rand

def generate(length):
    alphabets = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
    digits = "0123456789"
    characters = "[]{};:,.<>?/|!@#$%^&*()-_=+"

    # password contains at least one character from each set
    password = rand.choice(alphabets)
    password += rand.choice(digits)
    password += rand.choice(characters)

    # Generate the remaining password
    for i in range(length - 3): # subtracting 3 from length as 3 characters are already added
        password += rand.choice(alphabets+digits+characters)
    return password

length = int(input("Please enter the length of the password: "))
password = generate(length)
print("Password: ", password)