# -*- coding: utf-8 -*-
"""Codsoft_task_3(Rock_Paper_Scissor).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v3KwXgTw65BPealKlBAsyDrM74jY3oEI
"""

import random as rand

def get_computer_choice(): # this will return choice of computer using random
    return rand.choice(["Rock", "Paper", "Scissors"])

def Result(user, computer): # this will display winner by checking winning conditions
    if (user == computer):
        print("Match Tied")
    elif(user == "Rock" and computer == "Scissors" or user == "Paper" and computer == "Rock" or user == "Scissors" and computer == "Paper"):
        print("You Win")
    else:
        print("You Lose")

def play():
    flag = False
    while (flag == False):# take input from user until it enters a valid input
        choice = input("Please choose\n1. Rock\n2. Paper\n3. Scissors\n").capitalize()
        if(choice == "Rock" or choice == "Paper" or choice == "Scissors"):
            flag = True
        else:
            print("Invalid Input! Enter a valid one")

    computer = get_computer_choice()
    print("Your choice: ", choice, "\nComputer Choice: ", computer)
    Result(choice, computer)
    # ask user if he want to play again
    if input("Do you want to Play again?\nyes or no: ").capitalize() == "Yes":
        play()
    else:
      print("Thank you for playing this game")

play()