# -*- coding: utf-8 -*-
"""Codsoft_Task_2(Calculator).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pjGg1QwPJjtQz1o8fRFB6yfWQsvm7Cyv
"""

def sum(): # function to add two numbers
  num1 = input("please enter first number : ")
  num2 = input("please enter second number : ")
  return int(num1)+int(num2)
def sub(): # function to sub two numbers
  num1 = input("please enter first number : ")
  num2 = input("please enter second number : ")
  return int(num1)-int(num2)
def mul(): # function to multiply two numbers
  num1 = input("please enter first number : ")
  num2 = input("please enter second number : ")
  return int(num1)*int(num2)
def div(): # function to divide two numbers
  num1 = input("please enter first number : ")
  num2 = input("please enter second number : ")
  try: # as division by zero is not possible so this part will handle division by zero exception
    if (num2 == 0):
      raise Exception("division by zero is not possible ")
    else:
      return int(num1)/int(num2)
  except Exception as e:
    print("Error:" , e)
choice = 0
while(choice != 5):
  print("press 1 for addition")
  print("press 2 for subtraction")
  print("press 3 for multiplication")
  print("press 4 for division")
  print("press 5 to exit")
  print("\n")
  choice = input("Please enter your choice : ")
  print("\n")
  if (int(choice) == 1):
    result = sum()
    print("Answer = " , result)
    print("\n")
  elif (int(choice) == 2):
    result = sub()
    print("Answer = " , result)
    print("\n")
  elif (int(choice) == 3):
    result = mul()
    print("Answer = " , result)
    print("\n")
  elif (int(choice) == 4):
    result = div()
    print("Answer = " , result)
    print("\n")
  elif (int(choice) == 5):
    choice = int(5)
    print("Thank you" , "\n")
  else:
    print("you enter an invalid choice please enter a valid number" , "\n")